version: "3"
services:
  ddoshex:
    image: hexdemo
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.25"
          memory: 64M
      restart_policy:
        condition: on-failure